pkgname = "models"
output  = "internal/repository/models"
no-tests = true

[psql]
  dbname  = "postgres"
  host    = "localhost"
  port    = 5436
  user    = "postgres"
  pass    = "postgres"
  sslmode = "disable"
  blacklist = []
  whitelist = []

[psql.imports]
  all = ["github.com/volatiletech/null/v8", "github.com/lib/pq"]

[psql.replace]
  "null.JSON" = "types.JSON"
  "types.Int64Array" = "pq.Int64Array"
  "types.StringArray" = "pq.StringArray"
