// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CartItems          string
	Categories         string
	CustomerActivities string
	Customers          string
	OrderItems         string
	Orders             string
	ProductReviews     string
	Products           string
	RecommendationLogs string
	WishlistItems      string
}{
	CartItems:          "cart_items",
	Categories:         "categories",
	CustomerActivities: "customer_activities",
	Customers:          "customers",
	OrderItems:         "order_items",
	Orders:             "orders",
	ProductReviews:     "product_reviews",
	Products:           "products",
	RecommendationLogs: "recommendation_logs",
	WishlistItems:      "wishlist_items",
}
