// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// WishlistItem is an object representing the database table.
type WishlistItem struct {
	ID         string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	CustomerID string    `boil:"customer_id" json:"customer_id" toml:"customer_id" yaml:"customer_id"`
	ProductID  string    `boil:"product_id" json:"product_id" toml:"product_id" yaml:"product_id"`
	AddedAt    null.Time `boil:"added_at" json:"added_at,omitempty" toml:"added_at" yaml:"added_at,omitempty"`

	R *wishlistItemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L wishlistItemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WishlistItemColumns = struct {
	ID         string
	CustomerID string
	ProductID  string
	AddedAt    string
}{
	ID:         "id",
	CustomerID: "customer_id",
	ProductID:  "product_id",
	AddedAt:    "added_at",
}

var WishlistItemTableColumns = struct {
	ID         string
	CustomerID string
	ProductID  string
	AddedAt    string
}{
	ID:         "wishlist_items.id",
	CustomerID: "wishlist_items.customer_id",
	ProductID:  "wishlist_items.product_id",
	AddedAt:    "wishlist_items.added_at",
}

// Generated where

var WishlistItemWhere = struct {
	ID         whereHelperstring
	CustomerID whereHelperstring
	ProductID  whereHelperstring
	AddedAt    whereHelpernull_Time
}{
	ID:         whereHelperstring{field: "\"wishlist_items\".\"id\""},
	CustomerID: whereHelperstring{field: "\"wishlist_items\".\"customer_id\""},
	ProductID:  whereHelperstring{field: "\"wishlist_items\".\"product_id\""},
	AddedAt:    whereHelpernull_Time{field: "\"wishlist_items\".\"added_at\""},
}

// WishlistItemRels is where relationship names are stored.
var WishlistItemRels = struct {
	Customer string
	Product  string
}{
	Customer: "Customer",
	Product:  "Product",
}

// wishlistItemR is where relationships are stored.
type wishlistItemR struct {
	Customer *Customer `boil:"Customer" json:"Customer" toml:"Customer" yaml:"Customer"`
	Product  *Product  `boil:"Product" json:"Product" toml:"Product" yaml:"Product"`
}

// NewStruct creates a new relationship struct
func (*wishlistItemR) NewStruct() *wishlistItemR {
	return &wishlistItemR{}
}

func (o *WishlistItem) GetCustomer() *Customer {
	if o == nil {
		return nil
	}

	return o.R.GetCustomer()
}

func (r *wishlistItemR) GetCustomer() *Customer {
	if r == nil {
		return nil
	}

	return r.Customer
}

func (o *WishlistItem) GetProduct() *Product {
	if o == nil {
		return nil
	}

	return o.R.GetProduct()
}

func (r *wishlistItemR) GetProduct() *Product {
	if r == nil {
		return nil
	}

	return r.Product
}

// wishlistItemL is where Load methods for each relationship are stored.
type wishlistItemL struct{}

var (
	wishlistItemAllColumns            = []string{"id", "customer_id", "product_id", "added_at"}
	wishlistItemColumnsWithoutDefault = []string{"customer_id", "product_id"}
	wishlistItemColumnsWithDefault    = []string{"id", "added_at"}
	wishlistItemPrimaryKeyColumns     = []string{"id"}
	wishlistItemGeneratedColumns      = []string{}
)

type (
	// WishlistItemSlice is an alias for a slice of pointers to WishlistItem.
	// This should almost always be used instead of []WishlistItem.
	WishlistItemSlice []*WishlistItem
	// WishlistItemHook is the signature for custom WishlistItem hook methods
	WishlistItemHook func(context.Context, boil.ContextExecutor, *WishlistItem) error

	wishlistItemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	wishlistItemType                 = reflect.TypeOf(&WishlistItem{})
	wishlistItemMapping              = queries.MakeStructMapping(wishlistItemType)
	wishlistItemPrimaryKeyMapping, _ = queries.BindMapping(wishlistItemType, wishlistItemMapping, wishlistItemPrimaryKeyColumns)
	wishlistItemInsertCacheMut       sync.RWMutex
	wishlistItemInsertCache          = make(map[string]insertCache)
	wishlistItemUpdateCacheMut       sync.RWMutex
	wishlistItemUpdateCache          = make(map[string]updateCache)
	wishlistItemUpsertCacheMut       sync.RWMutex
	wishlistItemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var wishlistItemAfterSelectMu sync.Mutex
var wishlistItemAfterSelectHooks []WishlistItemHook

var wishlistItemBeforeInsertMu sync.Mutex
var wishlistItemBeforeInsertHooks []WishlistItemHook
var wishlistItemAfterInsertMu sync.Mutex
var wishlistItemAfterInsertHooks []WishlistItemHook

var wishlistItemBeforeUpdateMu sync.Mutex
var wishlistItemBeforeUpdateHooks []WishlistItemHook
var wishlistItemAfterUpdateMu sync.Mutex
var wishlistItemAfterUpdateHooks []WishlistItemHook

var wishlistItemBeforeDeleteMu sync.Mutex
var wishlistItemBeforeDeleteHooks []WishlistItemHook
var wishlistItemAfterDeleteMu sync.Mutex
var wishlistItemAfterDeleteHooks []WishlistItemHook

var wishlistItemBeforeUpsertMu sync.Mutex
var wishlistItemBeforeUpsertHooks []WishlistItemHook
var wishlistItemAfterUpsertMu sync.Mutex
var wishlistItemAfterUpsertHooks []WishlistItemHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WishlistItem) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wishlistItemAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WishlistItem) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wishlistItemBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WishlistItem) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wishlistItemAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WishlistItem) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wishlistItemBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WishlistItem) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wishlistItemAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WishlistItem) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wishlistItemBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WishlistItem) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wishlistItemAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WishlistItem) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wishlistItemBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WishlistItem) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range wishlistItemAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWishlistItemHook registers your hook function for all future operations.
func AddWishlistItemHook(hookPoint boil.HookPoint, wishlistItemHook WishlistItemHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		wishlistItemAfterSelectMu.Lock()
		wishlistItemAfterSelectHooks = append(wishlistItemAfterSelectHooks, wishlistItemHook)
		wishlistItemAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		wishlistItemBeforeInsertMu.Lock()
		wishlistItemBeforeInsertHooks = append(wishlistItemBeforeInsertHooks, wishlistItemHook)
		wishlistItemBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		wishlistItemAfterInsertMu.Lock()
		wishlistItemAfterInsertHooks = append(wishlistItemAfterInsertHooks, wishlistItemHook)
		wishlistItemAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		wishlistItemBeforeUpdateMu.Lock()
		wishlistItemBeforeUpdateHooks = append(wishlistItemBeforeUpdateHooks, wishlistItemHook)
		wishlistItemBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		wishlistItemAfterUpdateMu.Lock()
		wishlistItemAfterUpdateHooks = append(wishlistItemAfterUpdateHooks, wishlistItemHook)
		wishlistItemAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		wishlistItemBeforeDeleteMu.Lock()
		wishlistItemBeforeDeleteHooks = append(wishlistItemBeforeDeleteHooks, wishlistItemHook)
		wishlistItemBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		wishlistItemAfterDeleteMu.Lock()
		wishlistItemAfterDeleteHooks = append(wishlistItemAfterDeleteHooks, wishlistItemHook)
		wishlistItemAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		wishlistItemBeforeUpsertMu.Lock()
		wishlistItemBeforeUpsertHooks = append(wishlistItemBeforeUpsertHooks, wishlistItemHook)
		wishlistItemBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		wishlistItemAfterUpsertMu.Lock()
		wishlistItemAfterUpsertHooks = append(wishlistItemAfterUpsertHooks, wishlistItemHook)
		wishlistItemAfterUpsertMu.Unlock()
	}
}

// One returns a single wishlistItem record from the query.
func (q wishlistItemQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WishlistItem, error) {
	o := &WishlistItem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for wishlist_items")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WishlistItem records from the query.
func (q wishlistItemQuery) All(ctx context.Context, exec boil.ContextExecutor) (WishlistItemSlice, error) {
	var o []*WishlistItem

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to WishlistItem slice")
	}

	if len(wishlistItemAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WishlistItem records in the query.
func (q wishlistItemQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count wishlist_items rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q wishlistItemQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if wishlist_items exists")
	}

	return count > 0, nil
}

// Customer pointed to by the foreign key.
func (o *WishlistItem) Customer(mods ...qm.QueryMod) customerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CustomerID),
	}

	queryMods = append(queryMods, mods...)

	return Customers(queryMods...)
}

// Product pointed to by the foreign key.
func (o *WishlistItem) Product(mods ...qm.QueryMod) productQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProductID),
	}

	queryMods = append(queryMods, mods...)

	return Products(queryMods...)
}

// LoadCustomer allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (wishlistItemL) LoadCustomer(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWishlistItem interface{}, mods queries.Applicator) error {
	var slice []*WishlistItem
	var object *WishlistItem

	if singular {
		var ok bool
		object, ok = maybeWishlistItem.(*WishlistItem)
		if !ok {
			object = new(WishlistItem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWishlistItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWishlistItem))
			}
		}
	} else {
		s, ok := maybeWishlistItem.(*[]*WishlistItem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWishlistItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWishlistItem))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &wishlistItemR{}
		}
		args[object.CustomerID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &wishlistItemR{}
			}

			args[obj.CustomerID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`customers`),
		qm.WhereIn(`customers.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Customer")
	}

	var resultSlice []*Customer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Customer")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for customers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for customers")
	}

	if len(customerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Customer = foreign
		if foreign.R == nil {
			foreign.R = &customerR{}
		}
		foreign.R.WishlistItems = append(foreign.R.WishlistItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CustomerID == foreign.ID {
				local.R.Customer = foreign
				if foreign.R == nil {
					foreign.R = &customerR{}
				}
				foreign.R.WishlistItems = append(foreign.R.WishlistItems, local)
				break
			}
		}
	}

	return nil
}

// LoadProduct allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (wishlistItemL) LoadProduct(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWishlistItem interface{}, mods queries.Applicator) error {
	var slice []*WishlistItem
	var object *WishlistItem

	if singular {
		var ok bool
		object, ok = maybeWishlistItem.(*WishlistItem)
		if !ok {
			object = new(WishlistItem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWishlistItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWishlistItem))
			}
		}
	} else {
		s, ok := maybeWishlistItem.(*[]*WishlistItem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWishlistItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWishlistItem))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &wishlistItemR{}
		}
		args[object.ProductID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &wishlistItemR{}
			}

			args[obj.ProductID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`products`),
		qm.WhereIn(`products.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Product")
	}

	var resultSlice []*Product
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Product")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for products")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for products")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Product = foreign
		if foreign.R == nil {
			foreign.R = &productR{}
		}
		foreign.R.WishlistItems = append(foreign.R.WishlistItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ProductID == foreign.ID {
				local.R.Product = foreign
				if foreign.R == nil {
					foreign.R = &productR{}
				}
				foreign.R.WishlistItems = append(foreign.R.WishlistItems, local)
				break
			}
		}
	}

	return nil
}

// SetCustomer of the wishlistItem to the related item.
// Sets o.R.Customer to related.
// Adds o to related.R.WishlistItems.
func (o *WishlistItem) SetCustomer(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Customer) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"wishlist_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"customer_id"}),
		strmangle.WhereClause("\"", "\"", 2, wishlistItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CustomerID = related.ID
	if o.R == nil {
		o.R = &wishlistItemR{
			Customer: related,
		}
	} else {
		o.R.Customer = related
	}

	if related.R == nil {
		related.R = &customerR{
			WishlistItems: WishlistItemSlice{o},
		}
	} else {
		related.R.WishlistItems = append(related.R.WishlistItems, o)
	}

	return nil
}

// SetProduct of the wishlistItem to the related item.
// Sets o.R.Product to related.
// Adds o to related.R.WishlistItems.
func (o *WishlistItem) SetProduct(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Product) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"wishlist_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"product_id"}),
		strmangle.WhereClause("\"", "\"", 2, wishlistItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ProductID = related.ID
	if o.R == nil {
		o.R = &wishlistItemR{
			Product: related,
		}
	} else {
		o.R.Product = related
	}

	if related.R == nil {
		related.R = &productR{
			WishlistItems: WishlistItemSlice{o},
		}
	} else {
		related.R.WishlistItems = append(related.R.WishlistItems, o)
	}

	return nil
}

// WishlistItems retrieves all the records using an executor.
func WishlistItems(mods ...qm.QueryMod) wishlistItemQuery {
	mods = append(mods, qm.From("\"wishlist_items\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"wishlist_items\".*"})
	}

	return wishlistItemQuery{q}
}

// FindWishlistItem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWishlistItem(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WishlistItem, error) {
	wishlistItemObj := &WishlistItem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"wishlist_items\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, wishlistItemObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from wishlist_items")
	}

	if err = wishlistItemObj.doAfterSelectHooks(ctx, exec); err != nil {
		return wishlistItemObj, err
	}

	return wishlistItemObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WishlistItem) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no wishlist_items provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(wishlistItemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	wishlistItemInsertCacheMut.RLock()
	cache, cached := wishlistItemInsertCache[key]
	wishlistItemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			wishlistItemAllColumns,
			wishlistItemColumnsWithDefault,
			wishlistItemColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(wishlistItemType, wishlistItemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(wishlistItemType, wishlistItemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"wishlist_items\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"wishlist_items\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into wishlist_items")
	}

	if !cached {
		wishlistItemInsertCacheMut.Lock()
		wishlistItemInsertCache[key] = cache
		wishlistItemInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WishlistItem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WishlistItem) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	wishlistItemUpdateCacheMut.RLock()
	cache, cached := wishlistItemUpdateCache[key]
	wishlistItemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			wishlistItemAllColumns,
			wishlistItemPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update wishlist_items, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"wishlist_items\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, wishlistItemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(wishlistItemType, wishlistItemMapping, append(wl, wishlistItemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update wishlist_items row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for wishlist_items")
	}

	if !cached {
		wishlistItemUpdateCacheMut.Lock()
		wishlistItemUpdateCache[key] = cache
		wishlistItemUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q wishlistItemQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for wishlist_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for wishlist_items")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WishlistItemSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), wishlistItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"wishlist_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, wishlistItemPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in wishlistItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all wishlistItem")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WishlistItem) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no wishlist_items provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(wishlistItemColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	wishlistItemUpsertCacheMut.RLock()
	cache, cached := wishlistItemUpsertCache[key]
	wishlistItemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			wishlistItemAllColumns,
			wishlistItemColumnsWithDefault,
			wishlistItemColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			wishlistItemAllColumns,
			wishlistItemPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert wishlist_items, could not build update column list")
		}

		ret := strmangle.SetComplement(wishlistItemAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(wishlistItemPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert wishlist_items, could not build conflict column list")
			}

			conflict = make([]string, len(wishlistItemPrimaryKeyColumns))
			copy(conflict, wishlistItemPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"wishlist_items\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(wishlistItemType, wishlistItemMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(wishlistItemType, wishlistItemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert wishlist_items")
	}

	if !cached {
		wishlistItemUpsertCacheMut.Lock()
		wishlistItemUpsertCache[key] = cache
		wishlistItemUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WishlistItem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WishlistItem) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no WishlistItem provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), wishlistItemPrimaryKeyMapping)
	sql := "DELETE FROM \"wishlist_items\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from wishlist_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for wishlist_items")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q wishlistItemQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no wishlistItemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from wishlist_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for wishlist_items")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WishlistItemSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(wishlistItemBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), wishlistItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"wishlist_items\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, wishlistItemPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from wishlistItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for wishlist_items")
	}

	if len(wishlistItemAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WishlistItem) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWishlistItem(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WishlistItemSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WishlistItemSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), wishlistItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"wishlist_items\".* FROM \"wishlist_items\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, wishlistItemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WishlistItemSlice")
	}

	*o = slice

	return nil
}

// WishlistItemExists checks if the WishlistItem row exists.
func WishlistItemExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"wishlist_items\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if wishlist_items exists")
	}

	return exists, nil
}

// Exists checks if the WishlistItem row exists.
func (o *WishlistItem) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WishlistItemExists(ctx, exec, o.ID)
}
